### ISSUE TITLE
Collision between consecutive chords

### ISSUE THREAD

**Issue by alebabai** [alebabai/chords#6]
## what

If two chords are in a row and no text between them, then they will merge in the rendered html.
```md
В`[E]`сё идет `[Am]`по пла`[F]`ну.`[C]` `[E]`
```

<img width="220" alt="image" src="https://github.com/alebabai/chords/assets/19958900/17cdaffa-7e70-47dc-95e7-2b1542556bad">

## why

For now I found two possible approaches for chords rendering:
- absolute (current)
```css
.lyrics .chord {
  position: absolute;
  margin-top: -1.5rem;
}
```
- relative
```css
.lyrics .chord {
  position: relative;
  display: inline-block;
  top: -1.5em;
  width: 0;
}
 ```

And I don't know how to separate them without creating a gap between words.
